# Generated by Django 5.0.1 on 2024-01-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sobrenome', models.CharField(max_length=60)),
                ('tipo_sanguineo', models.CharField(max_length=3)),
                ('doador', models.BooleanField(default=False)),
            ],
        ),
    ]
