# Generated by Django 4.2.9 on 2024-01-16 19:04

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=120)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem_produto', stdimage.models.StdImageField(force_min_size=False, upload_to='produtos', variations={'thumb': (124, 124)})),
                ('descricao', models.TextField()),
            ],
        ),
    ]
